# Generated by Django 4.1.7 on 2023-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='c',
            field=models.TextField(blank=True),
        ),
    ]
