# Generated by Django 4.1.7 on 2023-02-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='c',
        ),
    ]
